apiVersion: v1
kind: Service
metadata:
  name: external-svc
  namespace: endpoints
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Endpoints
metadata:
  name: external-svc
  namespace: endpoints
subsets:
  - addresses:
        - ip: 192.168.140.173
    ports:
      - port: 80
        name: web
